# Generated by Django 5.0.2 on 2024-02-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserId', primary_key=True, serialize=False)),
                ('username', models.CharField(db_collation='Turkish_CI_AS', db_column='UserName', max_length=20)),
                ('password', models.CharField(db_collation='Turkish_CI_AS', db_column='Password', max_length=20)),
                ('email', models.CharField(db_collation='Turkish_CI_AS', db_column='Email', max_length=20)),
                ('favourites', models.TextField(blank=True, db_column='Favourites', null=True)),
                ('recipes', models.TextField(blank=True, db_column='Recipes', null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
