# Generated by Django 5.0.2 on 2024-03-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_user_email_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='favourites',
            new_name='favorites',
        ),
    ]
