# Generated by Django 5.0.2 on 2024-03-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_rename_favourites_user_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
