# Generated by Django 5.0.2 on 2024-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeid', models.AutoField(primary_key=True, serialize=False)),
                ('recipename', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.BinaryField(max_length='max')),
                ('ratingnum', models.IntegerField()),
                ('rating', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('image', models.BinaryField(max_length='max')),
            ],
            options={
                'db_table': 'Recipe',
                'managed': False,
            },
        ),
    ]
