# Generated by Django 5.0.2 on 2024-03-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.TextField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Default_pfp.svg/340px-Default_pfp.svg.png?20220226140232 '),
        ),
    ]
