# Generated by Django 5.0.2 on 2024-03-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0008_user_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favoritesid', models.AutoField(primary_key=True, serialize=False)),
                ('recipeid', models.IntegerField()),
            ],
            options={
                'db_table': 'Favorites',
                'managed': False,
            },
        ),
    ]
