# Generated by Django 5.0.2 on 2024-03-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0009_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='recipes',
            field=models.BinaryField(blank=True, max_length='max', null=True),
        ),
    ]
